// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKoeQ7_Pc8AJYkmhrtv7LgU9PH7PLnOxA',
    appId: '1:222922418762:web:e09261f05f06836d8814b3',
    messagingSenderId: '222922418762',
    projectId: 'mamty-efb09',
    authDomain: 'mamty-efb09.firebaseapp.com',
    storageBucket: 'mamty-efb09.firebasestorage.app',
    measurementId: 'G-9TWG9PG5NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr5rPqwqc_c7geFRFziyR-PYsINFmKf-I',
    appId: '1:222922418762:android:15395abfd57bf0ac8814b3',
    messagingSenderId: '222922418762',
    projectId: 'mamty-efb09',
    storageBucket: 'mamty-efb09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA4a0aWjUYsTaJJEY6Ukr8jfWU7y_b5dY',
    appId: '1:222922418762:ios:e9fa5207a3b735008814b3',
    messagingSenderId: '222922418762',
    projectId: 'mamty-efb09',
    storageBucket: 'mamty-efb09.firebasestorage.app',
    iosBundleId: 'com.example.mamaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA4a0aWjUYsTaJJEY6Ukr8jfWU7y_b5dY',
    appId: '1:222922418762:ios:e9fa5207a3b735008814b3',
    messagingSenderId: '222922418762',
    projectId: 'mamty-efb09',
    storageBucket: 'mamty-efb09.firebasestorage.app',
    iosBundleId: 'com.example.mamaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKoeQ7_Pc8AJYkmhrtv7LgU9PH7PLnOxA',
    appId: '1:222922418762:web:0ff080080206007a8814b3',
    messagingSenderId: '222922418762',
    projectId: 'mamty-efb09',
    authDomain: 'mamty-efb09.firebaseapp.com',
    storageBucket: 'mamty-efb09.firebasestorage.app',
    measurementId: 'G-SK9ZH68J8M',
  );
}
